### ISSUE TITLE
How to generate my own network like cusomer-loyality-Program ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [IBM/customer-loyalty-program#1]
I want to generate my own network like customer-loyalty-program, which should generate the same network with nodejs framework plus angularjs component as well. the architecture should be same as this loyalty program.

**Comment by raheelzubairy** [comment]
@ZaheerUdDeen I would recommend starting with first creating the blockchain network.  Once you have a .bna file which you can deploy, then you can look to implement the nodejs application which would interact with the network.  Here are some resources on the Composer API: https://hyperledger.github.io/composer/latest/api/api-doc-index
