### ISSUE TITLE
Clarification on terminology

### ISSUE THREAD

**Issue by arisAlexis** [IBM/customer-loyalty-program#11]
I couldn't find where to ask this so here it goes:

Is a partner here (a company) the same as a "membership of an organization" in the IBM cloud plans?

Is a member here (a customer redeeming points) the same as a "small peer" in the IBM cloud plans?

What are the limitations?

**Comment by raheelzubairy** [comment]
@arisAlexis 
In deployment presented in this code pattern, we just have one organization hosting on IBM Cloud and allowing the member and partner to be created by issuing them identity cards to access the network.  It could be enhanced on Fabric to have each partner as having "membership" on IBP, and issuing identity cards to members.  The peers would be part of each organization to keep the ledger synchronized.
