### ISSUE TITLE
How to update Partner information

### ISSUE THREAD

**Issue by gnurtcouq** [IBM/customer-loyalty-program#12]
Hi All,

I would like to have a process to change/update Parner's Information (e,g Name). How can I achieve this?

Thx in advance.

**Comment by gnurtcouq** [comment]
Hi All,

I would like to have a process to change/update Parner's Information (e,g Name). How can I achieve this?

Thx in advance.

**Comment by raheelzubairy** [comment]
@gnurtcouq you can use the ParticipantRegistry to update information of a participant.  As in the Partner here on this network. 
Here is some documentation regarding it: https://hyperledger.github.io/composer/latest/api/runtime-participantregistry#update

**Comment by gnurtcouq** [comment]
@raheelzubairy : thanks a lot. It work.
