### ISSUE TITLE
Issue with Partner permissions entry

### ISSUE THREAD

**Issue by kabram** [IBM/customer-loyalty-program#2]
I'm trying to understand the ins and outs of permissions and rules and couldn't figure this one out.
Is there is an issue with this partner rule condition:

//Partners Not to have access to other member accounts
rule PartnerAccessPartner {
    description: "Allow memebers to access only their profile"
    participant(p): "org.clp.biznet.Partner"
    operation: ALL
    resource(r): "org.clp.biznet.Partner"
    **condition: (r.getIdentifier() === p.getIdentifier())**
    action: DENY
}

I think the condition should be removed from this rule to make it effective - this seems to only block a partner from ALL operations on their own account.

**Comment by raheelzubairy** [comment]
@kabram Thanks! that is right.  I have updated the permissions (and updated descriptions)
