### ISSUE TITLE
Error in permissions.acl file

### ISSUE THREAD

**Issue by AlexRanda11** [IBM/customer-loyalty-program#3]
In the permissions.acl file, there is an error on line 81 and 83 (aliases are present when there is no condition), and that's throwing the following error: 

ParseException: Expected "condition:", "transaction", comment, end of line or whitespace but "a" found. File permissions.acl line 84 column 5
Command failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clp-network@0.0.1 prepublish: `composer archive create -t dir -n .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clp-network@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexanderalbasosi/.npm/_logs/2018-06-24T13_41_57_839Z-debug.log

Was fixed by removing the aliases (p for participant and r for resource).

**Comment by raheelzubairy** [comment]
Thank you @AlexAlBasosi 
Have made the correction to permissions.acl
