### ISSUE TITLE
Idcard error

### ISSUE THREAD

**Issue by swatikrishnani** [IBM/customer-loyalty-program#8]
Getting error when executing...
./createPeerAdmin.sh
Using composer-cli at v0.19.4
Typeerror: IdCard is not a constructor
Error: Unable to read file: /tmp/PeerAdmin@hlfv1.card
Typeerror: Admin connection is not a constructor

**Comment by raheelzubairy** [comment]
@swatikrishnani would you be able to provide more detail regarding the os?  It seems the card location maybe the issue here where its storing cards

**Comment by ljbennett62** [comment]
@swatikrishnani - so I am using "Using composer-cli at v0.19.19" - can you give this a try - it is working for me.

**Comment by swatikrishnani** [comment]
Yup it's working
