### ISSUE TITLE
member Registeration failed 

### ISSUE THREAD

**Issue by aazzim** [IBM/customer-loyalty-program#9]
peeradmincard created successfully through command **$ ./createPeerAdminCard.sh**  also i got the following output when run [ $ composer card list ] command

composer card list
The following Business Network Cards are available:

Connection Profile: hlfv1
┌─────────────────┬───────────┬──────────────────┐
│ Card Name       │ UserId    │ Business Network │
├─────────────────┼───────────┼──────────────────┤
│ PeerAdmin@hlfv1 │ PeerAdmin │                  │
└─────────────────┴───────────┴──────────────────┘
Issue composer card list --card <Card Name> to get details a specific card
Command succeeded

My problem is : when i opened the application at address [ http://localhost:8000/registerMember ] and entered everything like userid ..etc  i got the following error [ Card not found: admin@clp-network ] 

any advise please ?

**Comment by raheelzubairy** [comment]
@aazzim did you try running `composer card list --card` to see if the card was present

**Comment by ljbennett62** [comment]
@aazzim - curious if you ran the command Raheel suggested - as it worked for me. tx
